# Platform Addons PackageVariant for RAN cluster
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: addons-ran
spec:
  upstream:
    repo: nephio-workload-blueprints
    package: platform-addons
  downstream:
    repo: ran
    package: platform-addons
  pipeline:
    mutators:
      - image: ghcr.io/kptdev/krm-functions-catalog/apply-setters:v0.2
        configMap:
          cluster-name: ran
---
# Platform Addons PackageVariant for Core cluster
apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: addons-core
spec:
  upstream:
    repo: nephio-workload-blueprints
    package: platform-addons
  downstream:
    repo: core
    package: platform-addons
  pipeline:
    mutators:
      - image: ghcr.io/kptdev/krm-functions-catalog/apply-setters:v0.2
        configMap:
          cluster-name: core
